<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <groupId>org.wso2.custom</groupId>
  <version>0.1</version>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>org.wso2.custom.auth.functions</artifactId>
  <packaging>bundle</packaging>
  <name>Conditional Authentication - Custom Functions</name>
  <url>https://maven.apache.org</url>

  <repositories>
    <repository>
      <id>wso2-nexus-support</id>
      <name>WSO2 internal Repository</name>
      <url>https://support-maven.wso2.org/nexus/content/repositories/updates-2.0/</url>
    </repository>
    <repository>
      <id>wso2.releases</id>
      <name>WSO2 Releases Repository</name>
      <url>https://maven.wso2.org/nexus/content/repositories/releases/</url>
      <releases>
        <enabled>true</enabled>
        <updatePolicy>daily</updatePolicy>
        <checksumPolicy>ignore</checksumPolicy>
      </releases>
    </repository>
    <repository>
      <id>wso2.snapshots</id>
      <name>WSO2 Snapshot Repository</name>
      <url>https://maven.wso2.org/nexus/content/repositories/snapshots/</url>
      <snapshots>
        <enabled>true</enabled>
        <updatePolicy>daily</updatePolicy>
      </snapshots>
      <releases>
        <enabled>false</enabled>
      </releases>
    </repository>
    <repository>
      <id>wso2-nexus</id>
      <name>WSO2 internal Repository</name>
      <url>https://maven.wso2.org/nexus/content/groups/wso2-public/</url>
      <releases>
        <enabled>true</enabled>
        <updatePolicy>daily</updatePolicy>
        <checksumPolicy>ignore</checksumPolicy>
      </releases>
    </repository>
  </repositories>

  <dependencies>
    <dependency>
      <groupId>org.wso2.carbon.identity.framework</groupId>
      <artifactId>org.wso2.carbon.identity.application.authentication.framework</artifactId>
      <version>${identity.framework.version}</version>
    </dependency>
    <dependency>
      <groupId>org.wso2.carbon</groupId>
      <artifactId>org.wso2.carbon.utils</artifactId>
      <version>${carbon.kernel.version}</version>
    </dependency>
    <dependency>
      <groupId>org.wso2.orbit.graalvm.sdk</groupId>
      <artifactId>graal-sdk</artifactId>
      <version>22.3.4.wso2v1</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.6.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <version>3.2.0</version>
        <extensions>true</extensions>
        <configuration>
          <instructions>
            <Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
            <Bundle-Name>${project.artifactId}</Bundle-Name>
            <Private-Package>
              org.wso2.custom.auth.functions.internal
            </Private-Package>
            <Export-Package>
              !org.wso2.custom.auth.functions.internal,
              org.wso2.custom.auth.functions
            </Export-Package>
            <Import-Package>
              org.wso2.carbon.identity.application.common.*,
              org.wso2.carbon.user.api.*,
              org.wso2.carbon.identity.conditional.auth.functions.user.*,
              org.apache.commons.lang,
              org.apache.commons.logging,
              org.osgi.service.component,
              org.osgi.service.component.annotations,
              org.wso2.carbon,
              org.wso2.carbon.core.util,
              org.wso2.carbon.identity.core.util,
              org.wso2.carbon.identity.application.authentication.framework,
              org.wso2.carbon.identity.application.authentication.framework.util,
              org.wso2.carbon.identity.application.authentication.framework.exception,
              org.wso2.carbon.identity.application.authentication.framework.model,
              org.wso2.carbon.identity.application.authentication.framework.config.model.graph.js,
              org.wso2.carbon.identity.application.authentication.framework.config.model.graph,
              org.wso2.carbon.identity.application.authentication.framework.config.model,
              org.wso2.carbon.identity.application.authentication.framework.context,
              org.apache.commons.collections,
              org.wso2.carbon.registry.core.service,
              org.wso2.carbon.user.core,
              org.wso2.carbon.user.core.claim,
              org.wso2.carbon.user.core.service
            </Import-Package>
            <DynamicImport-Package>
              org.graalvm.polyglot
            </DynamicImport-Package>
          </instructions>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

  <properties>
    <identity.framework.version>7.8.23</identity.framework.version>
    <carbon.kernel.version>4.10.42</carbon.kernel.version>
    <carbon.identity.framework.version.range>[5.14.67, 8.0.0)</carbon.identity.framework.version.range>
  </properties>
</project>
